// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lidar.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lidar.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class GreetingDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Greeting> {
} _Greeting_default_instance_;
class TelemetryPointDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TelemetryPoint> {
} _TelemetryPoint_default_instance_;

namespace protobuf_lidar_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Greeting, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Greeting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Greeting, greeting_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TelemetryPoint, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TelemetryPoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TelemetryPoint, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TelemetryPoint, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TelemetryPoint, distance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TelemetryPoint, angle_),
  0,
  1,
  2,
  3,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 5, sizeof(Greeting)},
  { 6, 14, sizeof(TelemetryPoint)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Greeting_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TelemetryPoint_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "lidar.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _Greeting_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _TelemetryPoint_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Greeting_default_instance_.DefaultConstruct();
  _TelemetryPoint_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\013lidar.proto\"\034\n\010Greeting\022\020\n\010greeting\030\001 "
      "\002(\t\"G\n\016TelemetryPoint\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 "
      "\002(\005\022\020\n\010distance\030\003 \002(\002\022\r\n\005angle\030\004 \002(\002B\031\n\021"
      "org.virtuoso.slamB\004Slam"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 143);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lidar.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_lidar_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Greeting::kGreetingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Greeting::Greeting()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_lidar_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Greeting)
}
Greeting::Greeting(const Greeting& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  greeting_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_greeting()) {
    greeting_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.greeting_);
  }
  // @@protoc_insertion_point(copy_constructor:Greeting)
}

void Greeting::SharedCtor() {
  _cached_size_ = 0;
  greeting_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Greeting::~Greeting() {
  // @@protoc_insertion_point(destructor:Greeting)
  SharedDtor();
}

void Greeting::SharedDtor() {
  greeting_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Greeting::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Greeting::descriptor() {
  protobuf_lidar_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_lidar_2eproto::file_level_metadata[0].descriptor;
}

const Greeting& Greeting::default_instance() {
  protobuf_lidar_2eproto::InitDefaults();
  return *internal_default_instance();
}

Greeting* Greeting::New(::google::protobuf::Arena* arena) const {
  Greeting* n = new Greeting;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Greeting::Clear() {
// @@protoc_insertion_point(message_clear_start:Greeting)
  if (has_greeting()) {
    GOOGLE_DCHECK(!greeting_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*greeting_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Greeting::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Greeting)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string greeting = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_greeting()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->greeting().data(), this->greeting().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Greeting.greeting");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Greeting)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Greeting)
  return false;
#undef DO_
}

void Greeting::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Greeting)
  // required string greeting = 1;
  if (has_greeting()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->greeting().data(), this->greeting().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Greeting.greeting");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->greeting(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Greeting)
}

::google::protobuf::uint8* Greeting::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Greeting)
  // required string greeting = 1;
  if (has_greeting()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->greeting().data(), this->greeting().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Greeting.greeting");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->greeting(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Greeting)
  return target;
}

size_t Greeting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Greeting)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required string greeting = 1;
  if (has_greeting()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->greeting());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Greeting::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Greeting)
  GOOGLE_DCHECK_NE(&from, this);
  const Greeting* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Greeting>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Greeting)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Greeting)
    MergeFrom(*source);
  }
}

void Greeting::MergeFrom(const Greeting& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Greeting)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_greeting()) {
    set_has_greeting();
    greeting_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.greeting_);
  }
}

void Greeting::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Greeting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Greeting::CopyFrom(const Greeting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Greeting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Greeting::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void Greeting::Swap(Greeting* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Greeting::InternalSwap(Greeting* other) {
  greeting_.Swap(&other->greeting_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Greeting::GetMetadata() const {
  protobuf_lidar_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_lidar_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Greeting

// required string greeting = 1;
bool Greeting::has_greeting() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Greeting::set_has_greeting() {
  _has_bits_[0] |= 0x00000001u;
}
void Greeting::clear_has_greeting() {
  _has_bits_[0] &= ~0x00000001u;
}
void Greeting::clear_greeting() {
  greeting_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_greeting();
}
const ::std::string& Greeting::greeting() const {
  // @@protoc_insertion_point(field_get:Greeting.greeting)
  return greeting_.GetNoArena();
}
void Greeting::set_greeting(const ::std::string& value) {
  set_has_greeting();
  greeting_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Greeting.greeting)
}
#if LANG_CXX11
void Greeting::set_greeting(::std::string&& value) {
  set_has_greeting();
  greeting_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Greeting.greeting)
}
#endif
void Greeting::set_greeting(const char* value) {
  set_has_greeting();
  greeting_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Greeting.greeting)
}
void Greeting::set_greeting(const char* value, size_t size) {
  set_has_greeting();
  greeting_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Greeting.greeting)
}
::std::string* Greeting::mutable_greeting() {
  set_has_greeting();
  // @@protoc_insertion_point(field_mutable:Greeting.greeting)
  return greeting_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Greeting::release_greeting() {
  // @@protoc_insertion_point(field_release:Greeting.greeting)
  clear_has_greeting();
  return greeting_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Greeting::set_allocated_greeting(::std::string* greeting) {
  if (greeting != NULL) {
    set_has_greeting();
  } else {
    clear_has_greeting();
  }
  greeting_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), greeting);
  // @@protoc_insertion_point(field_set_allocated:Greeting.greeting)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TelemetryPoint::kXFieldNumber;
const int TelemetryPoint::kYFieldNumber;
const int TelemetryPoint::kDistanceFieldNumber;
const int TelemetryPoint::kAngleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TelemetryPoint::TelemetryPoint()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_lidar_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:TelemetryPoint)
}
TelemetryPoint::TelemetryPoint(const TelemetryPoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    reinterpret_cast<char*>(&angle_) -
    reinterpret_cast<char*>(&x_) + sizeof(angle_));
  // @@protoc_insertion_point(copy_constructor:TelemetryPoint)
}

void TelemetryPoint::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&x_, 0, reinterpret_cast<char*>(&angle_) -
    reinterpret_cast<char*>(&x_) + sizeof(angle_));
}

TelemetryPoint::~TelemetryPoint() {
  // @@protoc_insertion_point(destructor:TelemetryPoint)
  SharedDtor();
}

void TelemetryPoint::SharedDtor() {
}

void TelemetryPoint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TelemetryPoint::descriptor() {
  protobuf_lidar_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_lidar_2eproto::file_level_metadata[1].descriptor;
}

const TelemetryPoint& TelemetryPoint::default_instance() {
  protobuf_lidar_2eproto::InitDefaults();
  return *internal_default_instance();
}

TelemetryPoint* TelemetryPoint::New(::google::protobuf::Arena* arena) const {
  TelemetryPoint* n = new TelemetryPoint;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TelemetryPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:TelemetryPoint)
  if (_has_bits_[0 / 32] & 15u) {
    ::memset(&x_, 0, reinterpret_cast<char*>(&angle_) -
      reinterpret_cast<char*>(&x_) + sizeof(angle_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TelemetryPoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TelemetryPoint)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 x = 1;
      case 1: {
        if (tag == 8u) {
          set_has_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 y = 2;
      case 2: {
        if (tag == 16u) {
          set_has_y();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float distance = 3;
      case 3: {
        if (tag == 29u) {
          set_has_distance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &distance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float angle = 4;
      case 4: {
        if (tag == 37u) {
          set_has_angle();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &angle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TelemetryPoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TelemetryPoint)
  return false;
#undef DO_
}

void TelemetryPoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TelemetryPoint)
  // required int32 x = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->x(), output);
  }

  // required int32 y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->y(), output);
  }

  // required float distance = 3;
  if (has_distance()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->distance(), output);
  }

  // required float angle = 4;
  if (has_angle()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->angle(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:TelemetryPoint)
}

::google::protobuf::uint8* TelemetryPoint::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TelemetryPoint)
  // required int32 x = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->x(), target);
  }

  // required int32 y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->y(), target);
  }

  // required float distance = 3;
  if (has_distance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->distance(), target);
  }

  // required float angle = 4;
  if (has_angle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->angle(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TelemetryPoint)
  return target;
}

size_t TelemetryPoint::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:TelemetryPoint)
  size_t total_size = 0;

  if (has_x()) {
    // required int32 x = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());
  }

  if (has_y()) {
    // required int32 y = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->y());
  }

  if (has_distance()) {
    // required float distance = 3;
    total_size += 1 + 4;
  }

  if (has_angle()) {
    // required float angle = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
size_t TelemetryPoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TelemetryPoint)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required int32 x = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());

    // required int32 y = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->y());

    // required float distance = 3;
    total_size += 1 + 4;

    // required float angle = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TelemetryPoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TelemetryPoint)
  GOOGLE_DCHECK_NE(&from, this);
  const TelemetryPoint* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TelemetryPoint>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TelemetryPoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TelemetryPoint)
    MergeFrom(*source);
  }
}

void TelemetryPoint::MergeFrom(const TelemetryPoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TelemetryPoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 15u) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_distance()) {
      set_distance(from.distance());
    }
    if (from.has_angle()) {
      set_angle(from.angle());
    }
  }
}

void TelemetryPoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TelemetryPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TelemetryPoint::CopyFrom(const TelemetryPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TelemetryPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TelemetryPoint::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  return true;
}

void TelemetryPoint::Swap(TelemetryPoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TelemetryPoint::InternalSwap(TelemetryPoint* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(distance_, other->distance_);
  std::swap(angle_, other->angle_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TelemetryPoint::GetMetadata() const {
  protobuf_lidar_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_lidar_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TelemetryPoint

// required int32 x = 1;
bool TelemetryPoint::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TelemetryPoint::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
void TelemetryPoint::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
void TelemetryPoint::clear_x() {
  x_ = 0;
  clear_has_x();
}
::google::protobuf::int32 TelemetryPoint::x() const {
  // @@protoc_insertion_point(field_get:TelemetryPoint.x)
  return x_;
}
void TelemetryPoint::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:TelemetryPoint.x)
}

// required int32 y = 2;
bool TelemetryPoint::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TelemetryPoint::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
void TelemetryPoint::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
void TelemetryPoint::clear_y() {
  y_ = 0;
  clear_has_y();
}
::google::protobuf::int32 TelemetryPoint::y() const {
  // @@protoc_insertion_point(field_get:TelemetryPoint.y)
  return y_;
}
void TelemetryPoint::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:TelemetryPoint.y)
}

// required float distance = 3;
bool TelemetryPoint::has_distance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void TelemetryPoint::set_has_distance() {
  _has_bits_[0] |= 0x00000004u;
}
void TelemetryPoint::clear_has_distance() {
  _has_bits_[0] &= ~0x00000004u;
}
void TelemetryPoint::clear_distance() {
  distance_ = 0;
  clear_has_distance();
}
float TelemetryPoint::distance() const {
  // @@protoc_insertion_point(field_get:TelemetryPoint.distance)
  return distance_;
}
void TelemetryPoint::set_distance(float value) {
  set_has_distance();
  distance_ = value;
  // @@protoc_insertion_point(field_set:TelemetryPoint.distance)
}

// required float angle = 4;
bool TelemetryPoint::has_angle() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void TelemetryPoint::set_has_angle() {
  _has_bits_[0] |= 0x00000008u;
}
void TelemetryPoint::clear_has_angle() {
  _has_bits_[0] &= ~0x00000008u;
}
void TelemetryPoint::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
float TelemetryPoint::angle() const {
  // @@protoc_insertion_point(field_get:TelemetryPoint.angle)
  return angle_;
}
void TelemetryPoint::set_angle(float value) {
  set_has_angle();
  angle_ = value;
  // @@protoc_insertion_point(field_set:TelemetryPoint.angle)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
