// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/lidar.proto

#ifndef PROTOBUF_protobuf_2flidar_2eproto__INCLUDED
#define PROTOBUF_protobuf_2flidar_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_protobuf_2flidar_2eproto();
void protobuf_AssignDesc_protobuf_2flidar_2eproto();
void protobuf_ShutdownFile_protobuf_2flidar_2eproto();

class Greeting;
class Point;

// ===================================================================

class Greeting : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Greeting) */ {
 public:
  Greeting();
  virtual ~Greeting();

  Greeting(const Greeting& from);

  inline Greeting& operator=(const Greeting& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Greeting& default_instance();

  void Swap(Greeting* other);

  // implements Message ----------------------------------------------

  inline Greeting* New() const { return New(NULL); }

  Greeting* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Greeting& from);
  void MergeFrom(const Greeting& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Greeting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string greeting = 1;
  bool has_greeting() const;
  void clear_greeting();
  static const int kGreetingFieldNumber = 1;
  const ::std::string& greeting() const;
  void set_greeting(const ::std::string& value);
  void set_greeting(const char* value);
  void set_greeting(const char* value, size_t size);
  ::std::string* mutable_greeting();
  ::std::string* release_greeting();
  void set_allocated_greeting(::std::string* greeting);

  // @@protoc_insertion_point(class_scope:Greeting)
 private:
  inline void set_has_greeting();
  inline void clear_has_greeting();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr greeting_;
  friend void  protobuf_AddDesc_protobuf_2flidar_2eproto();
  friend void protobuf_AssignDesc_protobuf_2flidar_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2flidar_2eproto();

  void InitAsDefaultInstance();
  static Greeting* default_instance_;
};
// -------------------------------------------------------------------

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  void Swap(Point* other);

  // implements Message ----------------------------------------------

  inline Point* New() const { return New(NULL); }

  Point* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // required float distance = 3;
  bool has_distance() const;
  void clear_distance();
  static const int kDistanceFieldNumber = 3;
  float distance() const;
  void set_distance(float value);

  // required float angle = 4;
  bool has_angle() const;
  void clear_angle();
  static const int kAngleFieldNumber = 4;
  float angle() const;
  void set_angle(float value);

  // required bool end = 5;
  bool has_end() const;
  void clear_end();
  static const int kEndFieldNumber = 5;
  bool end() const;
  void set_end(bool value);

  // @@protoc_insertion_point(class_scope:Point)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_distance();
  inline void clear_has_distance();
  inline void set_has_angle();
  inline void clear_has_angle();
  inline void set_has_end();
  inline void clear_has_end();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  float distance_;
  float angle_;
  bool end_;
  friend void  protobuf_AddDesc_protobuf_2flidar_2eproto();
  friend void protobuf_AssignDesc_protobuf_2flidar_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2flidar_2eproto();

  void InitAsDefaultInstance();
  static Point* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Greeting

// required string greeting = 1;
inline bool Greeting::has_greeting() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Greeting::set_has_greeting() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Greeting::clear_has_greeting() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Greeting::clear_greeting() {
  greeting_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_greeting();
}
inline const ::std::string& Greeting::greeting() const {
  // @@protoc_insertion_point(field_get:Greeting.greeting)
  return greeting_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Greeting::set_greeting(const ::std::string& value) {
  set_has_greeting();
  greeting_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Greeting.greeting)
}
inline void Greeting::set_greeting(const char* value) {
  set_has_greeting();
  greeting_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Greeting.greeting)
}
inline void Greeting::set_greeting(const char* value, size_t size) {
  set_has_greeting();
  greeting_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Greeting.greeting)
}
inline ::std::string* Greeting::mutable_greeting() {
  set_has_greeting();
  // @@protoc_insertion_point(field_mutable:Greeting.greeting)
  return greeting_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Greeting::release_greeting() {
  // @@protoc_insertion_point(field_release:Greeting.greeting)
  clear_has_greeting();
  return greeting_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Greeting::set_allocated_greeting(::std::string* greeting) {
  if (greeting != NULL) {
    set_has_greeting();
  } else {
    clear_has_greeting();
  }
  greeting_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), greeting);
  // @@protoc_insertion_point(field_set_allocated:Greeting.greeting)
}

// -------------------------------------------------------------------

// Point

// required int32 x = 1;
inline bool Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Point::x() const {
  // @@protoc_insertion_point(field_get:Point.x)
  return x_;
}
inline void Point::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Point.x)
}

// required int32 y = 2;
inline bool Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Point::y() const {
  // @@protoc_insertion_point(field_get:Point.y)
  return y_;
}
inline void Point::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Point.y)
}

// required float distance = 3;
inline bool Point::has_distance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Point::set_has_distance() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Point::clear_has_distance() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Point::clear_distance() {
  distance_ = 0;
  clear_has_distance();
}
inline float Point::distance() const {
  // @@protoc_insertion_point(field_get:Point.distance)
  return distance_;
}
inline void Point::set_distance(float value) {
  set_has_distance();
  distance_ = value;
  // @@protoc_insertion_point(field_set:Point.distance)
}

// required float angle = 4;
inline bool Point::has_angle() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Point::set_has_angle() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Point::clear_has_angle() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Point::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline float Point::angle() const {
  // @@protoc_insertion_point(field_get:Point.angle)
  return angle_;
}
inline void Point::set_angle(float value) {
  set_has_angle();
  angle_ = value;
  // @@protoc_insertion_point(field_set:Point.angle)
}

// required bool end = 5;
inline bool Point::has_end() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Point::set_has_end() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Point::clear_has_end() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Point::clear_end() {
  end_ = false;
  clear_has_end();
}
inline bool Point::end() const {
  // @@protoc_insertion_point(field_get:Point.end)
  return end_;
}
inline void Point::set_end(bool value) {
  set_has_end();
  end_ = value;
  // @@protoc_insertion_point(field_set:Point.end)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2flidar_2eproto__INCLUDED
